// Code generated by protoc-gen-temporalvalidate. DO NOT EDIT.
package validation

import (
	fmt "fmt"
	v1 "go.temporal.io/api/common/v1"
	v11 "go.temporal.io/api/sdk/v1"
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// Validator is the implementation contract for functions used by enrolled RPCs.
type Validator[C any] interface {
	ValidateIDLength(C, string) error
	ValidateNamespace(C, string) error
	ValidateOperationNameLength(C, string) error
	ValidatePayload(C, *v1.Payload) error
	ValidateReasonLength(C, string) error
	ValidateServiceNameLength(C, string) error
	ValidateUserMetadata(C, *v11.UserMetadata) error
}

// Check detects stale generated code and incompatible annotations at startup.
func Check(name string, field protoreflect.FieldDescriptor) error {
	switch name {
	case "ValidateIDLength":
		if field.IsList() || field.IsMap() || field.Kind() != protoreflect.StringKind {
			return fmt.Errorf("%s does not support field %s", name, field.FullName())
		}
		return nil
	case "ValidateNamespace":
		if field.IsList() || field.IsMap() || field.Kind() != protoreflect.StringKind {
			return fmt.Errorf("%s does not support field %s", name, field.FullName())
		}
		return nil
	case "ValidateOperationNameLength":
		if field.IsList() || field.IsMap() || field.Kind() != protoreflect.StringKind {
			return fmt.Errorf("%s does not support field %s", name, field.FullName())
		}
		return nil
	case "ValidatePayload":
		if field.IsList() || field.IsMap() || field.Kind() != protoreflect.MessageKind {
			return fmt.Errorf("%s does not support field %s", name, field.FullName())
		}
		if field.Message().FullName() != "temporal.api.common.v1.Payload" {
			return fmt.Errorf("%s requires temporal.api.common.v1.Payload", name)
		}
		return nil
	case "ValidateReasonLength":
		if field.IsList() || field.IsMap() || field.Kind() != protoreflect.StringKind {
			return fmt.Errorf("%s does not support field %s", name, field.FullName())
		}
		return nil
	case "ValidateServiceNameLength":
		if field.IsList() || field.IsMap() || field.Kind() != protoreflect.StringKind {
			return fmt.Errorf("%s does not support field %s", name, field.FullName())
		}
		return nil
	case "ValidateUserMetadata":
		if field.IsList() || field.IsMap() || field.Kind() != protoreflect.MessageKind {
			return fmt.Errorf("%s does not support field %s", name, field.FullName())
		}
		if field.Message().FullName() != "temporal.api.sdk.v1.UserMetadata" {
			return fmt.Errorf("%s requires temporal.api.sdk.v1.UserMetadata", name)
		}
		return nil
	default:
		return fmt.Errorf("unknown validation function %q; regenerate API-Go", name)
	}
}

// Invoke calls the inferred method without a manual registration map.
func Invoke[C any](validator Validator[C], ctx C, name string, field protoreflect.FieldDescriptor, value protoreflect.Value) error {
	if err := Check(name, field); err != nil {
		return err
	}
	switch name {
	case "ValidateIDLength":
		return validator.ValidateIDLength(ctx, value.String())
	case "ValidateNamespace":
		return validator.ValidateNamespace(ctx, value.String())
	case "ValidateOperationNameLength":
		return validator.ValidateOperationNameLength(ctx, value.String())
	case "ValidatePayload":
		if !value.Message().IsValid() {
			return validator.ValidatePayload(ctx, nil)
		}
		typed, ok := value.Message().Interface().(*v1.Payload)
		if !ok {
			typed = &v1.Payload{}
			proto.Merge(typed, value.Message().Interface())
		}
		return validator.ValidatePayload(ctx, typed)
	case "ValidateReasonLength":
		return validator.ValidateReasonLength(ctx, value.String())
	case "ValidateServiceNameLength":
		return validator.ValidateServiceNameLength(ctx, value.String())
	case "ValidateUserMetadata":
		if !value.Message().IsValid() {
			return validator.ValidateUserMetadata(ctx, nil)
		}
		typed, ok := value.Message().Interface().(*v11.UserMetadata)
		if !ok {
			typed = &v11.UserMetadata{}
			proto.Merge(typed, value.Message().Interface())
		}
		return validator.ValidateUserMetadata(ctx, typed)
	default:
		return fmt.Errorf("unknown validation function %q", name)
	}
}
