package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"unicode"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

func main() {
	descriptor := flag.String("descriptor", "descriptor_set.pb", "API descriptor set")
	out := flag.String("out", "temporalproto/registry/services_gen.go", "generated service inventory")
	check := flag.Bool("check", false, "fail if the service inventory is stale")
	flag.Parse()
	if err := run(*descriptor, *out, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(set *descriptorpb.FileDescriptorSet) ([]byte, error) {
	var files []*descriptorpb.FileDescriptorProto
	for _, file := range set.GetFile() {
		if strings.HasPrefix(file.GetName(), "temporal/api/") && len(file.GetService()) > 0 {
			files = append(files, file)
		}
	}
	sort.Slice(files, func(i, j int) bool { return files[i].GetName() < files[j].GetName() })
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by genvalidationservices. DO NOT EDIT.\npackage registry\nimport (")
	for i, file := range files {
		path := strings.Split(file.GetOptions().GetGoPackage(), ";")[0]
		if !strings.HasPrefix(path, "go.temporal.io/api/") {
			return nil, fmt.Errorf("%s has no API go_package", file.GetName())
		}
		fmt.Fprintf(&output, "service%d %q\n", i, path)
	}
	fmt.Fprintln(&output, "\"google.golang.org/protobuf/reflect/protoreflect\"\n)")
	fmt.Fprintln(&output, "// Services returns every generated Temporal API service descriptor.\nfunc Services() []protoreflect.ServiceDescriptor { return []protoreflect.ServiceDescriptor{")
	for i, file := range files {
		name := strings.Map(func(r rune) rune {
			if unicode.IsLetter(r) || unicode.IsDigit(r) {
				return r
			}
			return '_'
		}, file.GetName())
		for j := range file.GetService() {
			fmt.Fprintf(&output, "service%d.File_%s.Services().Get(%d),\n", i, name, j)
		}
	}
	fmt.Fprintln(&output, "} }")
	return format.Source(output.Bytes())
}

func run(descriptor, out string, check bool) error {
	data, err := os.ReadFile(descriptor)
	if err != nil {
		return err
	}
	set := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(data, set); err != nil {
		return err
	}
	generated, err := generate(set)
	if err != nil {
		return err
	}
	if check {
		current, err := os.ReadFile(out)
		if err != nil {
			return err
		}
		if !bytes.Equal(current, generated) {
			return fmt.Errorf("%s is stale; run make validation-services", out)
		}
		return nil
	}
	return os.WriteFile(out, generated, 0o644)
}
