// Code generated by genvalidationservices. DO NOT EDIT.
package registry

import (
	service0 "go.temporal.io/api/operatorservice/v1"
	service1 "go.temporal.io/api/workflowservice/v1"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Services returns every generated Temporal API service descriptor.
func Services() []protoreflect.ServiceDescriptor {
	return []protoreflect.ServiceDescriptor{
		service0.File_temporal_api_operatorservice_v1_service_proto.Services().Get(0),
		service1.File_temporal_api_workflowservice_v1_service_proto.Services().Get(0),
	}
}
