// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporalvalidate/v1/annotations.proto

package temporalvalidate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server implements function; this metadata never executes a CEL expression.
type Rule struct {
	state     protoimpl.MessageState                  `protogen:"open.v1"`
	Function  *string                                 `protobuf:"bytes,1,opt,name=function" json:"function,omitempty"`
	FieldType *descriptorpb.FieldDescriptorProto_Type `protobuf:"varint,2,opt,name=field_type,json=fieldType,enum=google.protobuf.FieldDescriptorProto_Type" json:"field_type,omitempty"`
	// Required for message and enum fields; fully qualified without a leading dot.
	TypeName            *string  `protobuf:"bytes,3,opt,name=type_name,json=typeName" json:"type_name,omitempty"`
	CanonicalFieldNames []string `protobuf:"bytes,4,rep,name=canonical_field_names,json=canonicalFieldNames" json:"canonical_field_names,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_temporalvalidate_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_temporalvalidate_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_temporalvalidate_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetFunction() string {
	if x != nil && x.Function != nil {
		return *x.Function
	}
	return ""
}

func (x *Rule) GetFieldType() descriptorpb.FieldDescriptorProto_Type {
	if x != nil && x.FieldType != nil {
		return *x.FieldType
	}
	return descriptorpb.FieldDescriptorProto_Type(1)
}

func (x *Rule) GetTypeName() string {
	if x != nil && x.TypeName != nil {
		return *x.TypeName
	}
	return ""
}

func (x *Rule) GetCanonicalFieldNames() []string {
	if x != nil {
		return x.CanonicalFieldNames
	}
	return nil
}

// Enables request rejection and response warnings for a unary RPC.
type RPCValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	Ignored       *string                `protobuf:"bytes,2,opt,name=ignored" json:"ignored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCValidation) Reset() {
	*x = RPCValidation{}
	mi := &file_temporalvalidate_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCValidation) ProtoMessage() {}

func (x *RPCValidation) ProtoReflect() protoreflect.Message {
	mi := &file_temporalvalidate_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCValidation.ProtoReflect.Descriptor instead.
func (*RPCValidation) Descriptor() ([]byte, []int) {
	return file_temporalvalidate_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *RPCValidation) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *RPCValidation) GetIgnored() string {
	if x != nil && x.Ignored != nil {
		return *x.Ignored
	}
	return ""
}

var file_temporalvalidate_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Rule)(nil),
		Field:         900014,
		Name:          "temporalvalidate.v1.rule",
		Tag:           "bytes,900014,opt,name=rule",
		Filename:      "temporalvalidate/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         900015,
		Name:          "temporalvalidate.v1.canonical_rule_ignored",
		Tag:           "bytes,900015,opt,name=canonical_rule_ignored",
		Filename:      "temporalvalidate/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         900001,
		Name:          "temporalvalidate.v1.field_coverage_ignored",
		Tag:           "bytes,900001,opt,name=field_coverage_ignored",
		Filename:      "temporalvalidate/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         900010,
		Name:          "temporalvalidate.v1.validate_nested",
		Tag:           "varint,900010,opt,name=validate_nested",
		Filename:      "temporalvalidate/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         900011,
		Name:          "temporalvalidate.v1.nested_coverage_ignored",
		Tag:           "bytes,900011,opt,name=nested_coverage_ignored",
		Filename:      "temporalvalidate/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RPCValidation)(nil),
		Field:         900003,
		Name:          "temporalvalidate.v1.rpc_validation",
		Tag:           "bytes,900003,opt,name=rpc_validation",
		Filename:      "temporalvalidate/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Describes a reusable bool FieldOptions extension, not a field check.
	//
	// optional temporalvalidate.v1.Rule rule = 900014;
	E_Rule = &file_temporalvalidate_v1_annotations_proto_extTypes[0]
	// Permits different semantics for a canonical field; other coverage still applies.
	//
	// optional string canonical_rule_ignored = 900015;
	E_CanonicalRuleIgnored = &file_temporalvalidate_v1_annotations_proto_extTypes[1]
	// Records why validation belongs elsewhere or all field values are valid.
	//
	// optional string field_coverage_ignored = 900001;
	E_FieldCoverageIgnored = &file_temporalvalidate_v1_annotations_proto_extTypes[2]
	// Audits child fields in messages, list elements, and map message values.
	//
	// optional bool validate_nested = 900010;
	E_ValidateNested = &file_temporalvalidate_v1_annotations_proto_extTypes[3]
	// optional string nested_coverage_ignored = 900011;
	E_NestedCoverageIgnored = &file_temporalvalidate_v1_annotations_proto_extTypes[4]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional temporalvalidate.v1.RPCValidation rpc_validation = 900003;
	E_RpcValidation = &file_temporalvalidate_v1_annotations_proto_extTypes[5]
)

var File_temporalvalidate_v1_annotations_proto protoreflect.FileDescriptor

const file_temporalvalidate_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"%temporalvalidate/v1/annotations.proto\x12\x13temporalvalidate.v1\x1a google/protobuf/descriptor.proto\"\xbe\x01\n" +
	"\x04Rule\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x12I\n" +
	"\n" +
	"field_type\x18\x02 \x01(\x0e2*.google.protobuf.FieldDescriptorProto.TypeR\tfieldType\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x122\n" +
	"\x15canonical_field_names\x18\x04 \x03(\tR\x13canonicalFieldNames\"C\n" +
	"\rRPCValidation\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aignored\x18\x02 \x01(\tR\aignored:N\n" +
	"\x04rule\x12\x1d.google.protobuf.FieldOptions\x18\xae\xf76 \x01(\v2\x19.temporalvalidate.v1.RuleR\x04rule:U\n" +
	"\x16canonical_rule_ignored\x12\x1d.google.protobuf.FieldOptions\x18\xaf\xf76 \x01(\tR\x14canonicalRuleIgnored:U\n" +
	"\x16field_coverage_ignored\x12\x1d.google.protobuf.FieldOptions\x18\xa1\xf76 \x01(\tR\x14fieldCoverageIgnored:H\n" +
	"\x0fvalidate_nested\x12\x1d.google.protobuf.FieldOptions\x18\xaa\xf76 \x01(\bR\x0evalidateNested:W\n" +
	"\x17nested_coverage_ignored\x12\x1d.google.protobuf.FieldOptions\x18\xab\xf76 \x01(\tR\x15nestedCoverageIgnored:k\n" +
	"\x0erpc_validation\x12\x1e.google.protobuf.MethodOptions\x18\xa3\xf76 \x01(\v2\".temporalvalidate.v1.RPCValidationR\rrpcValidationB9Z7go.temporal.io/api/temporalvalidate/v1;temporalvalidate"

var (
	file_temporalvalidate_v1_annotations_proto_rawDescOnce sync.Once
	file_temporalvalidate_v1_annotations_proto_rawDescData []byte
)

func file_temporalvalidate_v1_annotations_proto_rawDescGZIP() []byte {
	file_temporalvalidate_v1_annotations_proto_rawDescOnce.Do(func() {
		file_temporalvalidate_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporalvalidate_v1_annotations_proto_rawDesc), len(file_temporalvalidate_v1_annotations_proto_rawDesc)))
	})
	return file_temporalvalidate_v1_annotations_proto_rawDescData
}

var file_temporalvalidate_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_temporalvalidate_v1_annotations_proto_goTypes = []any{
	(*Rule)(nil),          // 0: temporalvalidate.v1.Rule
	(*RPCValidation)(nil), // 1: temporalvalidate.v1.RPCValidation
	(descriptorpb.FieldDescriptorProto_Type)(0), // 2: google.protobuf.FieldDescriptorProto.Type
	(*descriptorpb.FieldOptions)(nil),           // 3: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),          // 4: google.protobuf.MethodOptions
}
var file_temporalvalidate_v1_annotations_proto_depIdxs = []int32{
	2, // 0: temporalvalidate.v1.Rule.field_type:type_name -> google.protobuf.FieldDescriptorProto.Type
	3, // 1: temporalvalidate.v1.rule:extendee -> google.protobuf.FieldOptions
	3, // 2: temporalvalidate.v1.canonical_rule_ignored:extendee -> google.protobuf.FieldOptions
	3, // 3: temporalvalidate.v1.field_coverage_ignored:extendee -> google.protobuf.FieldOptions
	3, // 4: temporalvalidate.v1.validate_nested:extendee -> google.protobuf.FieldOptions
	3, // 5: temporalvalidate.v1.nested_coverage_ignored:extendee -> google.protobuf.FieldOptions
	4, // 6: temporalvalidate.v1.rpc_validation:extendee -> google.protobuf.MethodOptions
	0, // 7: temporalvalidate.v1.rule:type_name -> temporalvalidate.v1.Rule
	1, // 8: temporalvalidate.v1.rpc_validation:type_name -> temporalvalidate.v1.RPCValidation
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	7, // [7:9] is the sub-list for extension type_name
	1, // [1:7] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_temporalvalidate_v1_annotations_proto_init() }
func file_temporalvalidate_v1_annotations_proto_init() {
	if File_temporalvalidate_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporalvalidate_v1_annotations_proto_rawDesc), len(file_temporalvalidate_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_temporalvalidate_v1_annotations_proto_goTypes,
		DependencyIndexes: file_temporalvalidate_v1_annotations_proto_depIdxs,
		MessageInfos:      file_temporalvalidate_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_temporalvalidate_v1_annotations_proto_extTypes,
	}.Build()
	File_temporalvalidate_v1_annotations_proto = out.File
	file_temporalvalidate_v1_annotations_proto_goTypes = nil
	file_temporalvalidate_v1_annotations_proto_depIdxs = nil
}
