// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package temporalvalidate

import (
	"google.golang.org/protobuf/proto"
)

// Marshal an object of type Rule to the protobuf v3 wire format
func (val *Rule) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type Rule from the protobuf v3 wire format
func (val *Rule) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *Rule) Size() int {
	return proto.Size(val)
}

// Equal returns whether two Rule values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *Rule) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *Rule
	switch t := that.(type) {
	case *Rule:
		that1 = t
	case Rule:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type RPCValidation to the protobuf v3 wire format
func (val *RPCValidation) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type RPCValidation from the protobuf v3 wire format
func (val *RPCValidation) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *RPCValidation) Size() int {
	return proto.Size(val)
}

// Equal returns whether two RPCValidation values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *RPCValidation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *RPCValidation
	switch t := that.(type) {
	case *RPCValidation:
		that1 = t
	case RPCValidation:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}
