// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporalvalidate/v1/rules.proto

package temporalvalidate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_temporalvalidate_v1_rules_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         901001,
		Name:          "temporalvalidate.v1.namespace",
		Tag:           "varint,901001,opt,name=namespace",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         901002,
		Name:          "temporalvalidate.v1.id_length",
		Tag:           "varint,901002,opt,name=id_length",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         901003,
		Name:          "temporalvalidate.v1.operation_name_length",
		Tag:           "varint,901003,opt,name=operation_name_length",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         901004,
		Name:          "temporalvalidate.v1.payload",
		Tag:           "varint,901004,opt,name=payload",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         901005,
		Name:          "temporalvalidate.v1.reason_length",
		Tag:           "varint,901005,opt,name=reason_length",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         901006,
		Name:          "temporalvalidate.v1.service_name_length",
		Tag:           "varint,901006,opt,name=service_name_length",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         901007,
		Name:          "temporalvalidate.v1.user_metadata",
		Tag:           "varint,901007,opt,name=user_metadata",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool namespace = 901001;
	E_Namespace = &file_temporalvalidate_v1_rules_proto_extTypes[0]
	// optional bool id_length = 901002;
	E_IdLength = &file_temporalvalidate_v1_rules_proto_extTypes[1]
	// optional bool operation_name_length = 901003;
	E_OperationNameLength = &file_temporalvalidate_v1_rules_proto_extTypes[2]
	// optional bool payload = 901004;
	E_Payload = &file_temporalvalidate_v1_rules_proto_extTypes[3]
	// optional bool reason_length = 901005;
	E_ReasonLength = &file_temporalvalidate_v1_rules_proto_extTypes[4]
	// optional bool service_name_length = 901006;
	E_ServiceNameLength = &file_temporalvalidate_v1_rules_proto_extTypes[5]
	// optional bool user_metadata = 901007;
	E_UserMetadata = &file_temporalvalidate_v1_rules_proto_extTypes[6]
)

var File_temporalvalidate_v1_rules_proto protoreflect.FileDescriptor

const file_temporalvalidate_v1_rules_proto_rawDesc = "" +
	"\n" +
	"\x1ftemporalvalidate/v1/rules.proto\x12\x13temporalvalidate.v1\x1a google/protobuf/descriptor.proto\x1a%temporalvalidate/v1/annotations.proto:d\n" +
	"\tnamespace\x12\x1d.google.protobuf.FieldOptions\x18\x89\xff6 \x01(\bB%\xf2\xba\xb7\x03 \n" +
	"\x11ValidateNamespace\x10\t\"\tnamespaceR\tnamespace:e\n" +
	"\tid_length\x12\x1d.google.protobuf.FieldOptions\x18\x8a\xff6 \x01(\bB'\xf2\xba\xb7\x03\"\n" +
	"\x10ValidateIDLength\x10\t\"\foperation_idR\bidLength:y\n" +
	"\x15operation_name_length\x12\x1d.google.protobuf.FieldOptions\x18\x8b\xff6 \x01(\bB$\xf2\xba\xb7\x03\x1f\n" +
	"\x1bValidateOperationNameLength\x10\tR\x13operationNameLength:s\n" +
	"\apayload\x12\x1d.google.protobuf.FieldOptions\x18\x8c\xff6 \x01(\bB8\xf2\xba\xb7\x033\n" +
	"\x0fValidatePayload\x10\v\x1a\x1etemporal.api.common.v1.PayloadR\apayload:c\n" +
	"\rreason_length\x12\x1d.google.protobuf.FieldOptions\x18\x8d\xff6 \x01(\bB\x1d\xf2\xba\xb7\x03\x18\n" +
	"\x14ValidateReasonLength\x10\tR\freasonLength:s\n" +
	"\x13service_name_length\x12\x1d.google.protobuf.FieldOptions\x18\x8e\xff6 \x01(\bB\"\xf2\xba\xb7\x03\x1d\n" +
	"\x19ValidateServiceNameLength\x10\tR\x11serviceNameLength:\x85\x01\n" +
	"\ruser_metadata\x12\x1d.google.protobuf.FieldOptions\x18\x8f\xff6 \x01(\bB?\xf2\xba\xb7\x03:\n" +
	"\x14ValidateUserMetadata\x10\v\x1a temporal.api.sdk.v1.UserMetadataR\fuserMetadataB9Z7go.temporal.io/api/temporalvalidate/v1;temporalvalidate"

var file_temporalvalidate_v1_rules_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_temporalvalidate_v1_rules_proto_depIdxs = []int32{
	0, // 0: temporalvalidate.v1.namespace:extendee -> google.protobuf.FieldOptions
	0, // 1: temporalvalidate.v1.id_length:extendee -> google.protobuf.FieldOptions
	0, // 2: temporalvalidate.v1.operation_name_length:extendee -> google.protobuf.FieldOptions
	0, // 3: temporalvalidate.v1.payload:extendee -> google.protobuf.FieldOptions
	0, // 4: temporalvalidate.v1.reason_length:extendee -> google.protobuf.FieldOptions
	0, // 5: temporalvalidate.v1.service_name_length:extendee -> google.protobuf.FieldOptions
	0, // 6: temporalvalidate.v1.user_metadata:extendee -> google.protobuf.FieldOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	0, // [0:7] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temporalvalidate_v1_rules_proto_init() }
func file_temporalvalidate_v1_rules_proto_init() {
	if File_temporalvalidate_v1_rules_proto != nil {
		return
	}
	file_temporalvalidate_v1_annotations_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporalvalidate_v1_rules_proto_rawDesc), len(file_temporalvalidate_v1_rules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_temporalvalidate_v1_rules_proto_goTypes,
		DependencyIndexes: file_temporalvalidate_v1_rules_proto_depIdxs,
		ExtensionInfos:    file_temporalvalidate_v1_rules_proto_extTypes,
	}.Build()
	File_temporalvalidate_v1_rules_proto = out.File
	file_temporalvalidate_v1_rules_proto_goTypes = nil
	file_temporalvalidate_v1_rules_proto_depIdxs = nil
}
