// Validation rules and coverage options for Temporal API messages.
// proto2 is required because predefined rules use extensions.

// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporalvalidate/v1/rules.proto

package temporalvalidate

import (
	reflect "reflect"
	"strconv"
	sync "sync"
	unsafe "unsafe"

	validate "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamicRuleScope int32

const (
	DYNAMIC_RULE_SCOPE_UNSPECIFIED DynamicRuleScope = 0
	DYNAMIC_RULE_SCOPE_GLOBAL      DynamicRuleScope = 1
	DYNAMIC_RULE_SCOPE_NAMESPACE   DynamicRuleScope = 2
)

// Enum value maps for DynamicRuleScope.
var (
	DynamicRuleScope_name = map[int32]string{
		0: "DYNAMIC_RULE_SCOPE_UNSPECIFIED",
		1: "DYNAMIC_RULE_SCOPE_GLOBAL",
		2: "DYNAMIC_RULE_SCOPE_NAMESPACE",
	}
	DynamicRuleScope_value = map[string]int32{
		"DYNAMIC_RULE_SCOPE_UNSPECIFIED": 0,
		"DYNAMIC_RULE_SCOPE_GLOBAL":      1,
		"DYNAMIC_RULE_SCOPE_NAMESPACE":   2,
	}
)

func (x DynamicRuleScope) Enum() *DynamicRuleScope {
	p := new(DynamicRuleScope)
	*p = x
	return p
}

func (x DynamicRuleScope) String() string {
	switch x {
	case DYNAMIC_RULE_SCOPE_UNSPECIFIED:
		return "Unspecified"
	case DYNAMIC_RULE_SCOPE_GLOBAL:
		return "Global"
	case DYNAMIC_RULE_SCOPE_NAMESPACE:
		return "Namespace"
	default:
		return strconv.Itoa(int(x))
	}

}

func (DynamicRuleScope) Descriptor() protoreflect.EnumDescriptor {
	return file_temporalvalidate_v1_rules_proto_enumTypes[0].Descriptor()
}

func (DynamicRuleScope) Type() protoreflect.EnumType {
	return &file_temporalvalidate_v1_rules_proto_enumTypes[0]
}

func (x DynamicRuleScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DynamicRuleScope) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DynamicRuleScope(num)
	return nil
}

// Deprecated: Use DynamicRuleScope.Descriptor instead.
func (DynamicRuleScope) EnumDescriptor() ([]byte, []int) {
	return file_temporalvalidate_v1_rules_proto_rawDescGZIP(), []int{0}
}

type DynamicRuleSpec struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Scope         *DynamicRuleScope                       `protobuf:"varint,1,opt,name=scope,enum=temporalvalidate.v1.DynamicRuleScope" json:"scope,omitempty"`
	FieldType     *descriptorpb.FieldDescriptorProto_Type `protobuf:"varint,2,opt,name=field_type,json=fieldType,enum=google.protobuf.FieldDescriptorProto_Type" json:"field_type,omitempty"`
	MessageType   *string                                 `protobuf:"bytes,3,opt,name=message_type,json=messageType" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicRuleSpec) Reset() {
	*x = DynamicRuleSpec{}
	mi := &file_temporalvalidate_v1_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicRuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicRuleSpec) ProtoMessage() {}

func (x *DynamicRuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_temporalvalidate_v1_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicRuleSpec.ProtoReflect.Descriptor instead.
func (*DynamicRuleSpec) Descriptor() ([]byte, []int) {
	return file_temporalvalidate_v1_rules_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicRuleSpec) GetScope() DynamicRuleScope {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return DYNAMIC_RULE_SCOPE_UNSPECIFIED
}

func (x *DynamicRuleSpec) GetFieldType() descriptorpb.FieldDescriptorProto_Type {
	if x != nil && x.FieldType != nil {
		return *x.FieldType
	}
	return descriptorpb.FieldDescriptorProto_Type(1)
}

func (x *DynamicRuleSpec) GetMessageType() string {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return ""
}

// Selects exhaustive request field validation or records why it is skipped.
type RequestValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	Ignored       *string                `protobuf:"bytes,2,opt,name=ignored" json:"ignored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestValidation) Reset() {
	*x = RequestValidation{}
	mi := &file_temporalvalidate_v1_rules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestValidation) ProtoMessage() {}

func (x *RequestValidation) ProtoReflect() protoreflect.Message {
	mi := &file_temporalvalidate_v1_rules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestValidation.ProtoReflect.Descriptor instead.
func (*RequestValidation) Descriptor() ([]byte, []int) {
	return file_temporalvalidate_v1_rules_proto_rawDescGZIP(), []int{1}
}

func (x *RequestValidation) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *RequestValidation) GetIgnored() string {
	if x != nil && x.Ignored != nil {
		return *x.Ignored
	}
	return ""
}

var file_temporalvalidate_v1_rules_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         900001,
		Name:          "temporalvalidate.v1.field_coverage_ignored",
		Tag:           "bytes,900001,opt,name=field_coverage_ignored",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*DynamicRuleSpec)(nil),
		Field:         900009,
		Name:          "temporalvalidate.v1.rule_spec",
		Tag:           "bytes,900009,opt,name=rule_spec",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         900002,
		Name:          "temporalvalidate.v1.dynamic_global_max_id_length",
		Tag:           "varint,900002,opt,name=dynamic_global_max_id_length",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         900003,
		Name:          "temporalvalidate.v1.dynamic_namespace_max_service_name_length",
		Tag:           "varint,900003,opt,name=dynamic_namespace_max_service_name_length",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         900004,
		Name:          "temporalvalidate.v1.dynamic_namespace_max_operation_name_length",
		Tag:           "varint,900004,opt,name=dynamic_namespace_max_operation_name_length",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         900005,
		Name:          "temporalvalidate.v1.dynamic_namespace_max_reason_length",
		Tag:           "varint,900005,opt,name=dynamic_namespace_max_reason_length",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         900006,
		Name:          "temporalvalidate.v1.dynamic_namespace_max_payload_size",
		Tag:           "varint,900006,opt,name=dynamic_namespace_max_payload_size",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         900007,
		Name:          "temporalvalidate.v1.dynamic_namespace_max_user_metadata_summary_size",
		Tag:           "varint,900007,opt,name=dynamic_namespace_max_user_metadata_summary_size",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         900008,
		Name:          "temporalvalidate.v1.dynamic_namespace_max_user_metadata_details_size",
		Tag:           "varint,900008,opt,name=dynamic_namespace_max_user_metadata_details_size",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RequestValidation)(nil),
		Field:         900001,
		Name:          "temporalvalidate.v1.request_validation",
		Tag:           "bytes,900001,opt,name=request_validation",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*validate.StringRules)(nil),
		ExtensionType: (*bool)(nil),
		Field:         10003,
		Name:          "temporalvalidate.v1.namespace",
		Tag:           "varint,10003,opt,name=namespace",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
	{
		ExtendedType:  (*validate.StringRules)(nil),
		ExtensionType: (*bool)(nil),
		Field:         10004,
		Name:          "temporalvalidate.v1.operation_id",
		Tag:           "varint,10004,opt,name=operation_id",
		Filename:      "temporalvalidate/v1/rules.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string field_coverage_ignored = 900001;
	E_FieldCoverageIgnored = &file_temporalvalidate_v1_rules_proto_extTypes[0]
	// optional temporalvalidate.v1.DynamicRuleSpec rule_spec = 900009;
	E_RuleSpec = &file_temporalvalidate_v1_rules_proto_extTypes[1]
	// optional bool dynamic_global_max_id_length = 900002;
	E_DynamicGlobalMaxIdLength = &file_temporalvalidate_v1_rules_proto_extTypes[2]
	// optional bool dynamic_namespace_max_service_name_length = 900003;
	E_DynamicNamespaceMaxServiceNameLength = &file_temporalvalidate_v1_rules_proto_extTypes[3]
	// optional bool dynamic_namespace_max_operation_name_length = 900004;
	E_DynamicNamespaceMaxOperationNameLength = &file_temporalvalidate_v1_rules_proto_extTypes[4]
	// optional bool dynamic_namespace_max_reason_length = 900005;
	E_DynamicNamespaceMaxReasonLength = &file_temporalvalidate_v1_rules_proto_extTypes[5]
	// optional bool dynamic_namespace_max_payload_size = 900006;
	E_DynamicNamespaceMaxPayloadSize = &file_temporalvalidate_v1_rules_proto_extTypes[6]
	// optional bool dynamic_namespace_max_user_metadata_summary_size = 900007;
	E_DynamicNamespaceMaxUserMetadataSummarySize = &file_temporalvalidate_v1_rules_proto_extTypes[7]
	// optional bool dynamic_namespace_max_user_metadata_details_size = 900008;
	E_DynamicNamespaceMaxUserMetadataDetailsSize = &file_temporalvalidate_v1_rules_proto_extTypes[8]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional temporalvalidate.v1.RequestValidation request_validation = 900001;
	E_RequestValidation = &file_temporalvalidate_v1_rules_proto_extTypes[9]
)

// Extension fields to validate.StringRules.
var (
	// Must be non-empty.
	//
	// optional bool namespace = 10003;
	E_Namespace = &file_temporalvalidate_v1_rules_proto_extTypes[10]
	// Must be non-empty.
	//
	// optional bool operation_id = 10004;
	E_OperationId = &file_temporalvalidate_v1_rules_proto_extTypes[11]
)

var File_temporalvalidate_v1_rules_proto protoreflect.FileDescriptor

const file_temporalvalidate_v1_rules_proto_rawDesc = "" +
	"\n" +
	"\x1ftemporalvalidate/v1/rules.proto\x12\x13temporalvalidate.v1\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/descriptor.proto\"\xbc\x01\n" +
	"\x0fDynamicRuleSpec\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.temporalvalidate.v1.DynamicRuleScopeR\x05scope\x12I\n" +
	"\n" +
	"field_type\x18\x02 \x01(\x0e2*.google.protobuf.FieldDescriptorProto.TypeR\tfieldType\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\"G\n" +
	"\x11RequestValidation\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aignored\x18\x02 \x01(\tR\aignored*w\n" +
	"\x10DynamicRuleScope\x12\"\n" +
	"\x1eDYNAMIC_RULE_SCOPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DYNAMIC_RULE_SCOPE_GLOBAL\x10\x01\x12 \n" +
	"\x1cDYNAMIC_RULE_SCOPE_NAMESPACE\x10\x02:U\n" +
	"\x16field_coverage_ignored\x12\x1d.google.protobuf.FieldOptions\x18\xa1\xf76 \x01(\tR\x14fieldCoverageIgnored:b\n" +
	"\trule_spec\x12\x1d.google.protobuf.FieldOptions\x18\xa9\xf76 \x01(\v2$.temporalvalidate.v1.DynamicRuleSpecR\bruleSpec:j\n" +
	"\x1cdynamic_global_max_id_length\x12\x1d.google.protobuf.FieldOptions\x18\xa2\xf76 \x01(\bB\tʺ\xb7\x03\x04\b\x01\x10\tR\x18dynamicGlobalMaxIdLength:\x83\x01\n" +
	")dynamic_namespace_max_service_name_length\x12\x1d.google.protobuf.FieldOptions\x18\xa3\xf76 \x01(\bB\tʺ\xb7\x03\x04\b\x02\x10\tR$dynamicNamespaceMaxServiceNameLength:\x87\x01\n" +
	"+dynamic_namespace_max_operation_name_length\x12\x1d.google.protobuf.FieldOptions\x18\xa4\xf76 \x01(\bB\tʺ\xb7\x03\x04\b\x02\x10\tR&dynamicNamespaceMaxOperationNameLength:x\n" +
	"#dynamic_namespace_max_reason_length\x12\x1d.google.protobuf.FieldOptions\x18\xa5\xf76 \x01(\bB\tʺ\xb7\x03\x04\b\x02\x10\tR\x1fdynamicNamespaceMaxReasonLength:\x96\x01\n" +
	"\"dynamic_namespace_max_payload_size\x12\x1d.google.protobuf.FieldOptions\x18\xa6\xf76 \x01(\bB)ʺ\xb7\x03$\b\x02\x10\v\x1a\x1etemporal.api.common.v1.PayloadR\x1edynamicNamespaceMaxPayloadSize:\xb2\x01\n" +
	"0dynamic_namespace_max_user_metadata_summary_size\x12\x1d.google.protobuf.FieldOptions\x18\xa7\xf76 \x01(\bB+ʺ\xb7\x03&\b\x02\x10\v\x1a temporal.api.sdk.v1.UserMetadataR*dynamicNamespaceMaxUserMetadataSummarySize:\xb2\x01\n" +
	"0dynamic_namespace_max_user_metadata_details_size\x12\x1d.google.protobuf.FieldOptions\x18\xa8\xf76 \x01(\bB+ʺ\xb7\x03&\b\x02\x10\v\x1a temporal.api.sdk.v1.UserMetadataR*dynamicNamespaceMaxUserMetadataDetailsSize:w\n" +
	"\x12request_validation\x12\x1e.google.protobuf.MethodOptions\x18\xa1\xf76 \x01(\v2&.temporalvalidate.v1.RequestValidationR\x11requestValidation:\x8a\x01\n" +
	"\tnamespace\x12\x19.buf.validate.StringRules\x18\x93N \x01(\bBP\xc2HM\n" +
	"K\n" +
	"!temporalvalidate.string.namespace\x12\x15namespace is required\x1a\x0fthis.size() > 0R\tnamespace:\x95\x01\n" +
	"\foperation_id\x12\x19.buf.validate.StringRules\x18\x94N \x01(\bBV\xc2HS\n" +
	"Q\n" +
	"$temporalvalidate.string.operation_id\x12\x18operation_id is required\x1a\x0fthis.size() > 0R\voperationIdB9Z7go.temporal.io/api/temporalvalidate/v1;temporalvalidate"

var (
	file_temporalvalidate_v1_rules_proto_rawDescOnce sync.Once
	file_temporalvalidate_v1_rules_proto_rawDescData []byte
)

func file_temporalvalidate_v1_rules_proto_rawDescGZIP() []byte {
	file_temporalvalidate_v1_rules_proto_rawDescOnce.Do(func() {
		file_temporalvalidate_v1_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporalvalidate_v1_rules_proto_rawDesc), len(file_temporalvalidate_v1_rules_proto_rawDesc)))
	})
	return file_temporalvalidate_v1_rules_proto_rawDescData
}

var file_temporalvalidate_v1_rules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporalvalidate_v1_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_temporalvalidate_v1_rules_proto_goTypes = []any{
	(DynamicRuleScope)(0),                       // 0: temporalvalidate.v1.DynamicRuleScope
	(*DynamicRuleSpec)(nil),                     // 1: temporalvalidate.v1.DynamicRuleSpec
	(*RequestValidation)(nil),                   // 2: temporalvalidate.v1.RequestValidation
	(descriptorpb.FieldDescriptorProto_Type)(0), // 3: google.protobuf.FieldDescriptorProto.Type
	(*descriptorpb.FieldOptions)(nil),           // 4: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),          // 5: google.protobuf.MethodOptions
	(*validate.StringRules)(nil),                // 6: buf.validate.StringRules
}
var file_temporalvalidate_v1_rules_proto_depIdxs = []int32{
	0,  // 0: temporalvalidate.v1.DynamicRuleSpec.scope:type_name -> temporalvalidate.v1.DynamicRuleScope
	3,  // 1: temporalvalidate.v1.DynamicRuleSpec.field_type:type_name -> google.protobuf.FieldDescriptorProto.Type
	4,  // 2: temporalvalidate.v1.field_coverage_ignored:extendee -> google.protobuf.FieldOptions
	4,  // 3: temporalvalidate.v1.rule_spec:extendee -> google.protobuf.FieldOptions
	4,  // 4: temporalvalidate.v1.dynamic_global_max_id_length:extendee -> google.protobuf.FieldOptions
	4,  // 5: temporalvalidate.v1.dynamic_namespace_max_service_name_length:extendee -> google.protobuf.FieldOptions
	4,  // 6: temporalvalidate.v1.dynamic_namespace_max_operation_name_length:extendee -> google.protobuf.FieldOptions
	4,  // 7: temporalvalidate.v1.dynamic_namespace_max_reason_length:extendee -> google.protobuf.FieldOptions
	4,  // 8: temporalvalidate.v1.dynamic_namespace_max_payload_size:extendee -> google.protobuf.FieldOptions
	4,  // 9: temporalvalidate.v1.dynamic_namespace_max_user_metadata_summary_size:extendee -> google.protobuf.FieldOptions
	4,  // 10: temporalvalidate.v1.dynamic_namespace_max_user_metadata_details_size:extendee -> google.protobuf.FieldOptions
	5,  // 11: temporalvalidate.v1.request_validation:extendee -> google.protobuf.MethodOptions
	6,  // 12: temporalvalidate.v1.namespace:extendee -> buf.validate.StringRules
	6,  // 13: temporalvalidate.v1.operation_id:extendee -> buf.validate.StringRules
	1,  // 14: temporalvalidate.v1.rule_spec:type_name -> temporalvalidate.v1.DynamicRuleSpec
	2,  // 15: temporalvalidate.v1.request_validation:type_name -> temporalvalidate.v1.RequestValidation
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	14, // [14:16] is the sub-list for extension type_name
	2,  // [2:14] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_temporalvalidate_v1_rules_proto_init() }
func file_temporalvalidate_v1_rules_proto_init() {
	if File_temporalvalidate_v1_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporalvalidate_v1_rules_proto_rawDesc), len(file_temporalvalidate_v1_rules_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 12,
			NumServices:   0,
		},
		GoTypes:           file_temporalvalidate_v1_rules_proto_goTypes,
		DependencyIndexes: file_temporalvalidate_v1_rules_proto_depIdxs,
		EnumInfos:         file_temporalvalidate_v1_rules_proto_enumTypes,
		MessageInfos:      file_temporalvalidate_v1_rules_proto_msgTypes,
		ExtensionInfos:    file_temporalvalidate_v1_rules_proto_extTypes,
	}.Build()
	File_temporalvalidate_v1_rules_proto = out.File
	file_temporalvalidate_v1_rules_proto_goTypes = nil
	file_temporalvalidate_v1_rules_proto_depIdxs = nil
}
