// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package temporalvalidate

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

// Marshal an object of type DynamicRuleSpec to the protobuf v3 wire format
func (val *DynamicRuleSpec) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type DynamicRuleSpec from the protobuf v3 wire format
func (val *DynamicRuleSpec) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *DynamicRuleSpec) Size() int {
	return proto.Size(val)
}

// Equal returns whether two DynamicRuleSpec values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *DynamicRuleSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *DynamicRuleSpec
	switch t := that.(type) {
	case *DynamicRuleSpec:
		that1 = t
	case DynamicRuleSpec:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type RequestValidation to the protobuf v3 wire format
func (val *RequestValidation) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type RequestValidation from the protobuf v3 wire format
func (val *RequestValidation) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *RequestValidation) Size() int {
	return proto.Size(val)
}

// Equal returns whether two RequestValidation values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *RequestValidation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *RequestValidation
	switch t := that.(type) {
	case *RequestValidation:
		that1 = t
	case RequestValidation:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

var (
	DynamicRuleScope_shorthandValue = map[string]int32{
		"Unspecified": 0,
		"Global":      1,
		"Namespace":   2,
	}
)

// DynamicRuleScopeFromString parses a DynamicRuleScope value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to DynamicRuleScope
func DynamicRuleScopeFromString(s string) (DynamicRuleScope, error) {
	if v, ok := DynamicRuleScope_value[s]; ok {
		return DynamicRuleScope(v), nil
	} else if v, ok := DynamicRuleScope_shorthandValue[s]; ok {
		return DynamicRuleScope(v), nil
	}
	return DynamicRuleScope(0), fmt.Errorf("%s is not a valid DynamicRuleScope", s)
}
